default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>image.png
  host: localhost
  port: 5432
  username: postgres
  password: admin


development:
  <<: *default
  database: finance_manager_development

test:
  <<: *default
  database: finance_manager_test

production:
  url: <%= ENV["DATABASE_URL"]%>
  <<: *default
  database: finance_manager_production
  username: finance_manager
  password: <%= ENV["FINANCE_MANAGER_DATABASE_PASSWORD"] %>
